// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// HandlerInterface is an autogenerated mock type for the HandlerInterface type
type HandlerInterface struct {
	mock.Mock
}

// GetMovies provides a mock function with given fields: w, r
func (_m *HandlerInterface) GetMovies(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
