// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/andreastihor/stockbit/models"
	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

// InsertMovie provides a mock function with given fields: _a0
func (_m *RepositoryInterface) InsertMovie(_a0 models.Movie) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Movie) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
