// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/andreastihor/stockbit/models"
	mock "github.com/stretchr/testify/mock"
)

// ServiceInterface is an autogenerated mock type for the ServiceInterface type
type ServiceInterface struct {
	mock.Mock
}

// GetMovies provides a mock function with given fields: params
func (_m *ServiceInterface) GetMovies(params *models.Params) ([]*models.Movie, error) {
	ret := _m.Called(params)

	var r0 []*models.Movie
	if rf, ok := ret.Get(0).(func(*models.Params) []*models.Movie); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Movie)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Params) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
