// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: models/movie.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParamsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination string `protobuf:"bytes,1,opt,name=pagination,json=page,proto3" json:"pagination,omitempty"`
	Search     string `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *ParamsProto) Reset() {
	*x = ParamsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamsProto) ProtoMessage() {}

func (x *ParamsProto) ProtoReflect() protoreflect.Message {
	mi := &file_models_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamsProto.ProtoReflect.Descriptor instead.
func (*ParamsProto) Descriptor() ([]byte, []int) {
	return file_models_movie_proto_rawDescGZIP(), []int{0}
}

func (x *ParamsProto) GetPagination() string {
	if x != nil {
		return x.Pagination
	}
	return ""
}

func (x *ParamsProto) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type MovieProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year   string `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	ImdbID string `protobuf:"bytes,3,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Poster string `protobuf:"bytes,5,opt,name=poster,proto3" json:"poster,omitempty"`
}

func (x *MovieProto) Reset() {
	*x = MovieProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieProto) ProtoMessage() {}

func (x *MovieProto) ProtoReflect() protoreflect.Message {
	mi := &file_models_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieProto.ProtoReflect.Descriptor instead.
func (*MovieProto) Descriptor() ([]byte, []int) {
	return file_models_movie_proto_rawDescGZIP(), []int{1}
}

func (x *MovieProto) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieProto) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MovieProto) GetImdbID() string {
	if x != nil {
		return x.ImdbID
	}
	return ""
}

func (x *MovieProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MovieProto) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

var File_models_movie_proto protoreflect.FileDescriptor

var file_models_movie_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x0a, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x22, 0x7a, 0x0a, 0x0a,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x32, 0x3d, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x73,
	0x12, 0x12, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x2e, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x4d, 0x6f, 0x76,
	0x69, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_movie_proto_rawDescOnce sync.Once
	file_models_movie_proto_rawDescData = file_models_movie_proto_rawDesc
)

func file_models_movie_proto_rawDescGZIP() []byte {
	file_models_movie_proto_rawDescOnce.Do(func() {
		file_models_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_movie_proto_rawDescData)
	})
	return file_models_movie_proto_rawDescData
}

var file_models_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_movie_proto_goTypes = []interface{}{
	(*ParamsProto)(nil), // 0: movie.ParamsProto
	(*MovieProto)(nil),  // 1: movie.MovieProto
}
var file_models_movie_proto_depIdxs = []int32{
	0, // 0: movie.Service.GetMovies:input_type -> movie.ParamsProto
	1, // 1: movie.Service.GetMovies:output_type -> movie.MovieProto
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_movie_proto_init() }
func file_models_movie_proto_init() {
	if File_models_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_movie_proto_goTypes,
		DependencyIndexes: file_models_movie_proto_depIdxs,
		MessageInfos:      file_models_movie_proto_msgTypes,
	}.Build()
	File_models_movie_proto = out.File
	file_models_movie_proto_rawDesc = nil
	file_models_movie_proto_goTypes = nil
	file_models_movie_proto_depIdxs = nil
}
